[package]
name = "teensy"
version = "0.1.0"
authors = ["Connor Postma <connor.postma@gmail.com>", "Branan Riley <me@branan.info>"]
edition = "2018"

[dependencies]
volatile = "0.2.6"
bit_field = "0.9.0"
